config/routes.rb
Website::Application.routes.draw do

  root :to => "users#index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :username, :sign_times, :total_signin_times
  before_save {
    self.username = username.downcase
    self.total_signin_times = 0 unless self.total_signin_times
  }
  before_create :create_remember_token

  validates :username, uniqueness: true

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      flash.now[:error] = 'wrong username & password combination.'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {
        :signed_users => online_num("signed"),
        :anonymous_users => online_num("anony")
        }.to_json
      }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        @user.signin_times = 1
        sign_in @user
        format.html { redirect_to root_path }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
require 'Digest'

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    set_last_visit_time
    set_user_signin_times(user)
    self.current_user = user
  end

  def signed_in?
    cookies[:last_visit] = Time.now if cookies[:last_visit].nil?
    current_times = ((Time.now - cookies[:last_visit].to_time) / 60).to_i
    if current_user
      current_user.update_attribute(:total_signin_times, current_user.total_signin_times + current_times)
    else
      cookies[:current_times] = cookies[:current_times].to_i + current_times
    end
    record_sessions
    set_last_visit_time
    !current_user.nil?
  end

  def online_num(opt)
    md5_regex = /^([a-fA-F0-9]{32})$/
    num = 0
    case opt
    when "all" # all users num
      num = $redis.keys.count
    when "anony" # anonymous users num
      $redis.keys.each { |k| num += 1 if (k =~ md5_regex) }
    when "signed" # signed users num
      $redis.keys.each { |k| num += 1 unless (k =~ md5_regex) }
    end
    num
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by_remember_token(remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    self.current_user = nil
    cookies.delete(:remember_token)
    cookies.delete(:last_visit)
    cookies.delete(:current_times)
  end

  private
  def record_sessions
    if current_user
      name = current_user.username
    else
      name = Digest::MD5.hexdigest "#{request.env['HTTP_USER_AGENT']} #{request.env['REMOTE_ADDR']}"
    end
    $redis.set(name, Time.now)
    $redis.expire(name, 5 * 60)
  end

  def set_last_visit_time
    cookies.permanent[:last_visit] = Time.now
  end

  def set_user_signin_times(user)
    user.update_attribute(:signin_times, user.signin_times + 1)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '注册', new_user_path %>

<div>
  现在总共有 <%= online_num("signed") %> 个注册用户在查看这个网站，有 <%= online_num("anony") %> 个陌生人在查看这个网站
</div>

<% if signed_in? %>
  <div>
    <%= current_user.username %> 谢谢你登录了我们网站！你已经登录了 <%= current_user.signin_times %> 次了，总共登录时间是 <%= current_user.total_signin_times %> 分钟。
  </div>
  <div><%= link_to "注销", signout_path, method: "delete" %></div>
<% else %>
  <div>
    你好，陌生人！你没有登录，或者你还没有注册，但是你已经浏览这个页面 <%= cookies[:current_times] %> 分钟了。
  </div>
  <div><%= link_to "登录", signin_path, method: "get" %></div>
<% end %>

<div>在线总人数：<%= online_num("all") %></div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>